spring:
  cloud:
    gateway:
      routes:
  
        - id: LIKES
          uri: lb://LIKES-SERVER
          predicates:
            - Path=/likes/**
             
        - id: SONG
          uri: lb://SONG-SERVER
          predicates:
            - Path=/song/**
            
        - id: SIGNUP
          uri: lb://SIGNUP-SERVER
          predicates:
            - Path=/api/**
            
        - id: PLAYLIST
          uri: lb://PLAYLIST-SERVER
          predicates:
            - Path=/playlist/**
            
            